import type { Metadata } from "next";
import { Toaster } from "sonner";
import "./globals.css";

export const metadata: Metadata = {
  title: "Khmer Calendar Admin Dashboard",
  description: "Generated by Khmer Calendar Admin Dashboard",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        {children}
        <Toaster
          position="top-right"
          richColors
          closeButton
          toastOptions={{
            className: "rounded-xl border border-border bg-background shadow-lg",
            descriptionClassName: "text-muted-foreground"
          }}
        />
      </body>
    </html>
  );
}
